# Workflow to deploy the Flask application to an AWS EC2 instance
name: Deploy Python/Flask App to AWS EC2

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    environment:
      name: production
      url: http://hemanttyrezone.in

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}

        script: |
          set -e # Exit immediately if a command exits with a non-zero status.
          
          PROJECT_PATH="/home/ubuntu/flaskapp/hemanttyres"
          
          echo "Navigating to project directory: $PROJECT_PATH"
          cd $PROJECT_PATH
          
          echo "Pulling latest code from GitHub..."
          git pull origin main
          
          echo "Installing/updating Python dependencies..."
          # This is the corrected line without the asterisks
          /home/ubuntu/flaskapp/venv/bin/pip install -r requirements.txt
          
          echo "Restarting application service..."
          sudo systemctl restart flaskapp.service
          
          echo "Verifying application service status..."
          sudo systemctl is-active --quiet flaskapp.service
          
          echo "✅ Deployment successful!"